version: "3.8"

services:
  redis:
    image: redis:6.2.6-alpine
    env_file:
      - .env
    expose:
      - "6379"
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    volumes:
      - redis_data:/data
  
  node-producer:
    build:
      context: ./node-producer
    depends_on:
      - redis
    command: node app.js

  rust-consumer:
    build:
      context: ./rust-client
    depends_on:
      - redis
      - node-producer
    command: rust-client

volumes:
  redis_data:
